# app.py
def main():
    print("Hello from Jenkins CI pipeline!")
    with open("build/output.txt", "w") as f:
        f.write("This file was generated by the pipeline.\n")
        f.write("Build successful!\n")

if __name__ == "__main__":
    main()
